name: Sprech
options:
  bundleIdPrefix: com.sprech
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "0.1.4"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"

targets:
  Sprech:
    type: application
    platform: macOS
    sources:
      - path: Sources
        group: Sources
      - path: Sprech/Resources
        group: Resources
    settings:
      base:
        PRODUCT_NAME: Sprech
        PRODUCT_BUNDLE_IDENTIFIER: com.sprech.app
        INFOPLIST_FILE: Sprech/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_HARDENED_RUNTIME: "YES"
        CODE_SIGN_ENTITLEMENTS: Sprech/Resources/Sprech.entitlements
        LD_RUNPATH_SEARCH_PATHS: 
          - "$(inherited)"
          - "@executable_path/../Frameworks"
    dependencies: []
    postBuildScripts: []

# TODO: Re-enable MLX package when xcodegen package resolution is fixed
# The MLX-Swift package has many dependencies that cause xcodegen to hang
# during project generation. For now, building without on-device ML features.
# 
# packages:
#   MLX:
#     url: https://github.com/ml-explore/mlx-swift
#     from: "0.15.0"
