name: Sprech
options:
  bundleIdPrefix: com.sprech
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"

targets:
  Sprech:
    type: application
    platform: macOS
    sources:
      - Sprech
    settings:
      base:
        PRODUCT_NAME: Sprech
        PRODUCT_BUNDLE_IDENTIFIER: com.sprech.app
        INFOPLIST_FILE: Sprech/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_HARDENED_RUNTIME: "YES"
        CODE_SIGN_ENTITLEMENTS: Sprech/Resources/Sprech.entitlements
    dependencies: []
    postBuildScripts: []

packages:
  MLX:
    url: https://github.com/ml-explore/mlx-swift
    from: "0.15.0"
