name: Sprech
targets:
  Sprech:
    type: application
    platform: macOS
    sources: [Sources, Sprech/Resources]
  SprechTests:
    type: bundle.unit-test
    platform: macOS
    sources: [Tests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Sprech

schemes:
  Sprech:
    build:
      targets:
        Sprech: all
    test:
      targets:
        - SprechTests
